### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by GFWisshit** [happy-turtle/oit-per-pixel-linked-list#1]
Your work inspired me. Thank you.
I upload my oit-implement ,have little improvement, more simpler code,and (maybe) no odd bugs.

**Comment by happy-turtle** [comment]
> Your work inspired me. Thank you.
> I upload my oit-implement ,have little improvement, more simpler code,and (maybe) no odd bugs.

Hi, thanks a lot, I am happy that repository helped someone. I looked at your code, it is a lot cleaner, very well done! It's way easier than my implementation and still works better. I am surprised you are still working with floats in the list, I thought that would be a performance killer. But your scene runs really smooth even on my onboard-graphics.
