### ISSUE TITLE
Off-Axis Camera View Issue

### ISSUE THREAD

**Issue by mlathrop-bell** [happy-turtle/oit-per-pixel-linked-list#2]
First, thanks for creating this! I downloaded the sample code but I encountered an issue as I started moving the camera around. See this GIF attached. Any ideas what might be causing this? 
![unity-issue](https://user-images.githubusercontent.com/77791949/146814404-35d82bb2-f08e-4571-9564-86984cbea1d9.gif)

**Comment by happy-turtle** [comment]
Hi, are you referring to the blocky artifacts in the cubes? Those can happen if the buffer size is too small. Did you try to increase the parameter listSizeMultiplier? Increasing this parameter will increase the buffer size. I could add a short description for this in the readme.

**Comment by happy-turtle** [comment]
[commit 2f7e5d4](https://github.com/happy-turtle/oit-per-pixel-linked-list/commit/2f7e5d4f8eabb1ff4329d87ba3948284a7a02891) might help as well
