### ISSUE TITLE
Incorrect stride?

### ISSUE THREAD

**Issue by bpepers-me** [happy-turtle/oit-per-pixel-linked-list#3]
In OrderIndependentTransparency.cs you define the buffer stride as:

`int bufferStride = sizeof(float) * 5 + sizeof(uint);`

But the actual struct has 5 float and 2 uints so it should be:

`int bufferStride = sizeof(float) * 5 + sizeof(uint) * 2;`

Perhaps this wasn't updated when coverage was added to the struct?

**Comment by happy-turtle** [comment]
Yes, I think you are absolutely right, thanks! That means the buffer is smaller than expected. Maybe fixing this will reduce the overall occurence of rendering errors.

**Comment by happy-turtle** [comment]
Should be fixed with [2f7e5d4](https://github.com/happy-turtle/oit-per-pixel-linked-list/commit/2f7e5d4f8eabb1ff4329d87ba3948284a7a02891).
